### PR TITLE
Update riscv-router.md

### PR DESCRIPTION
**Pull request by sethp**

### CODE REVIEW

**Comment by sethp** [comment]
Oh man, this gave me hives: I know the point is to send a notification for the change, but I feel like I asked for feedback and immediately said "NO FEEDBACK FROM YOU."

@dougli1sqrd some ideas:

- We turn on [email notifications](https://github.com/rustbox/discussion/settings/notifications/edit) for push events
- We decide to use PRs as a place for discussion, not purely notification, and include some notion like "if no feedback for X days, assume OK" around when it ought to get merged?
- We set up a robot (github actions?) that sends emails or some other notification on push
- We set up a robot (either the merge queue thing, or an action) to auto-merge PRs, possibly with a comment saying "hey, there's no feedback expected here" so I can at least _pretend_
- Mebe a PR template that says "this is intended to be immediately merged, not a request for feedback"?
 
Or, you just say "Seth, just do the damn thing lol" and I'll drop it.

**Comment by dougli1sqrd** [comment]
Ha oh I didn't know we could setup email notifs for push! That's cool.

Can you elaborate on 'but I feel like I asked for feedback and immediately said "NO FEEDBACK FROM YOU."'? Who is saying "no feedback"? Are you saying you're just getting infinite notifications now?

* Turning on email notifs sounds like a great place to start?

**Comment by sethp** [comment]
> Can you elaborate on 'but I feel like I asked for feedback and immediately said "NO FEEDBACK FROM YOU."'? Who is saying "no feedback"? Are you saying you're just getting infinite notifications now?

No, I just feel like I said "hey Eric what do you think of this?" when I created the "request", and when I merged it with no description or details or discussion I said "just kidding I don't care." It's a weird flex: it only works because you & I chatted about this out-of-band, and when I see a no-context no-discussion PR like this elsewhere I think "ok, so in order to contribute I must first establish a relationship some other way," which feels off-putting to me.

Pushing directly to main is also an exclusive members-only club thing, but at least it's honest about it :upside_down_face:

**Comment by sethp** [comment]
So, I realize this is the wrong place & quite possibly format to have the discussion: I opened up #11 instead.

**Pull request merged**
